# Generated by Django 6.0.7 on 2026-08-04 17:45

import airport.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("airport", "0002_order_route_flight_ticket_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="airport",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to=airport.models.airport_image_file_path
            ),
        ),
        migrations.AddField(
            model_name="crew",
            name="photo",
            field=models.ImageField(
                blank=True, null=True, upload_to=airport.models.crew_photo_file_path
            ),
        ),
    ]
