# Generated by Django 6.0.7 on 2026-08-13 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("airport", "0003_airport_image_crew_photo"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="ticket",
            name="unique_ticket_flight_row_seat",
        ),
        migrations.AddField(
            model_name="flight",
            name="status",
            field=models.CharField(
                choices=[
                    ("scheduled", "Scheduled"),
                    ("delayed", "Delayed"),
                    ("cancelled", "Cancelled"),
                ],
                default="scheduled",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[("confirmed", "Confirmed"), ("cancelled", "Cancelled")],
                default="confirmed",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="ticket",
            name="status",
            field=models.CharField(
                choices=[("active", "Active"), ("cancelled", "Cancelled")],
                default="active",
                max_length=20,
            ),
        ),
        migrations.AddConstraint(
            model_name="ticket",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "active")),
                fields=("flight", "row", "seat"),
                name="unique_ticket_flight_row_seat",
            ),
        ),
    ]
