[project]
name = "airport-api"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "django>=6.0.7",
    "django-filter>=26.1",
    "djangorestframework>=3.17.1",
    "djangorestframework-simplejwt>=5.5.1",
    "drf-spectacular>=0.30.0",
    "pillow>=12.3.0",
    "psycopg2-binary>=2.9.12",
    "python-decouple>=3.8",
]

[dependency-groups]
dev = [
    "black>=26.5.1",
    "coverage>=7.15.2",
    "django-debug-toolbar>=7.0.0",
    "django-stubs>=6.0.7",
    "flake8>=7.3.0",
    "flake8-quotes>=3.4.0",
    "flake8-variables-names>=0.0.6",
    "pep8-naming>=0.15.1",
    "pytest>=9.1.1",
]
